name: QA checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint source files
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Lint source files
        run: npm run lint

  build:
    name: Build package
    needs: lint
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: Build package
        run: npm run build
