name: QA checks

on:
  pull_request:
    branches:
      - main

jobs:
  qa:
    name: Code Quality Node ${{ matrix.node }}
    runs-on: [self-hosted, Linux]
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22, 24]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier

      - name: Lint source files
        run: npm run lint

      - name: Check types
        run: npm run typecheck

      - name: Build package
        run: npm run build

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: 'Report Coverage'
        if: matrix.node == 22 && always()
        uses: davelosert/vitest-coverage-report-action@v2
